ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "color_index" integer;

UPDATE "workspaces" SET "color_index" = CASE "color"
  WHEN '#FF9100' THEN 1  WHEN '#FFDEB3' THEN 1
  WHEN '#F9FF00' THEN 2  WHEN '#FEFFB3' THEN 2
  WHEN '#00FF06' THEN 3  WHEN '#B3FFB4' THEN 3
  WHEN '#00FFDD' THEN 4  WHEN '#B3FFF5' THEN 4
  WHEN '#0064FF' THEN 5  WHEN '#B3D1FF' THEN 5
  WHEN '#B400FF' THEN 6  WHEN '#E8B3FF' THEN 6
  WHEN '#FF00CE' THEN 7  WHEN '#FFB3F0' THEN 7
  WHEN '#FF0000' THEN 8  WHEN '#FFB3B3' THEN 8
  ELSE NULL
END WHERE "color" IS NOT NULL;

ALTER TABLE "workspaces" DROP COLUMN IF EXISTS "color";
