import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import workspacesRouter from "./workspaces";
import mapsRouter from "./maps";
import cardsRouter from "./cards";
import connectionsRouter from "./connections";
import myTasksRouter from "./myTasks";
import tasksSearchRouter from "./tasksSearch";
import commentsRouter, { taskRouter as taskCommentsRouter } from "./comments";
import workspaceTasksRouter from "./workspaceTasks";
import workspaceActivitiesRouter from "./workspaceActivities";
import recentMapsRouter from "./recentMaps";
import mapsSearchRouter from "./mapsSearch";
import storageRouter from "./storage";
import sidebarRouter from "./sidebar";
import preferencesRouter from "./preferences";
import textElementsRouter from "./textElements";
import shapesRouter from "./shapes";
import strategyRouter from "./strategy";
import taskTemplatesRouter from "./taskTemplates";
import taskLinksRouter from "./taskLinks";
import googleCalendarRouter from "./integrations/google-calendar";
import meetingsRouter from "./meetings";
import { meRouter as ssoMeRouter, publicRouter as ssoPublicRouter } from "./sso";
import { internalRouter } from "./internal";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/auth/me", ssoMeRouter);
router.use("/public", ssoPublicRouter);
router.use("/internal", internalRouter);
router.use("/users", usersRouter);
router.use("/workspaces", workspacesRouter);
router.use("/workspaces/:workspaceId/maps", mapsRouter);
router.use("/workspaces/:workspaceId/maps/:mapId/cards", cardsRouter);
router.use("/workspaces/:workspaceId/maps/:mapId/cards", commentsRouter);
router.use("/workspaces/:workspaceId/maps/:mapId/connections", connectionsRouter);
router.use("/workspaces/:workspaceId/maps/:mapId/text-elements", textElementsRouter);
router.use("/workspaces/:workspaceId/maps/:mapId/shapes", shapesRouter);
router.use("/workspaces/:workspaceId/strategy", strategyRouter);
router.use("/workspaces/:workspaceId/tasks", workspaceTasksRouter);
router.use("/workspaces/:workspaceId/activities", workspaceActivitiesRouter);
router.use("/workspaces/:workspaceId/tasks/:taskId", taskCommentsRouter);
router.use("/workspaces/:workspaceId/tasks/:taskId", taskLinksRouter);
router.use("/my-tasks", myTasksRouter);
router.use("/tasks", tasksSearchRouter);
router.use("/task-templates", taskTemplatesRouter);
router.use("/maps/recent", recentMapsRouter);
router.use("/maps/search", mapsSearchRouter);
router.use("/sidebar", sidebarRouter);
router.use("/preferences", preferencesRouter);
router.use("/integrations/google-calendar", googleCalendarRouter);
router.use("/meetings", meetingsRouter);
router.use(storageRouter);

export default router;
