import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import workspacesRouter from "./workspaces";
import mapsRouter from "./maps";
import cardsRouter from "./cards";
import connectionsRouter from "./connections";
import myTasksRouter from "./myTasks";
import tasksSearchRouter from "./tasksSearch";
import commentsRouter, { taskRouter as taskCommentsRouter } from "./comments";
import workspaceTasksRouter from "./workspaceTasks";
import recentMapsRouter from "./recentMaps";
import storageRouter from "./storage";
import sidebarRouter from "./sidebar";
import textElementsRouter from "./textElements";
import shapesRouter from "./shapes";
import taskTemplatesRouter from "./taskTemplates";
import googleCalendarRouter from "./integrations/google-calendar";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/workspaces", workspacesRouter);
router.use("/workspaces/:workspaceId/maps", mapsRouter);
router.use("/workspaces/:workspaceId/maps/:mapId/cards", cardsRouter);
router.use("/workspaces/:workspaceId/maps/:mapId/cards", commentsRouter);
router.use("/workspaces/:workspaceId/maps/:mapId/connections", connectionsRouter);
router.use("/workspaces/:workspaceId/maps/:mapId/text-elements", textElementsRouter);
router.use("/workspaces/:workspaceId/maps/:mapId/shapes", shapesRouter);
router.use("/workspaces/:workspaceId/tasks", workspaceTasksRouter);
router.use("/workspaces/:workspaceId/tasks/:taskId", taskCommentsRouter);
router.use("/my-tasks", myTasksRouter);
router.use("/tasks", tasksSearchRouter);
router.use("/task-templates", taskTemplatesRouter);
router.use("/maps/recent", recentMapsRouter);
router.use("/sidebar", sidebarRouter);
router.use("/integrations/google-calendar", googleCalendarRouter);
router.use(storageRouter);

export default router;
