// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mindtask-vibes/ElectricCoral.tsx": () => import("../components/mockups/mindtask-vibes/ElectricCoral.tsx"),
  "./components/mockups/mindtask-vibes/MidnightFocus.tsx": () => import("../components/mockups/mindtask-vibes/MidnightFocus.tsx"),
  "./components/mockups/mindtask-vibes/TerracottaParchment.tsx": () => import("../components/mockups/mindtask-vibes/TerracottaParchment.tsx")
};
